development:
  adapter: postgresql
  encoding: unicode
  database: base_app_dev
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: base_app_test
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: db_base_app
  host: localhost
  pool: 5
  timeout: 5000
